services:
  mongo:
    container_name: where2watch_mongo
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config: